services:
  # BANCO DE DADOS
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
   bridge:
    build: ./backend # Point to your backend folder
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DATABASE_URL: postgresql://user_local:password_local@db:5432/my_local_db
    depends_on:
      - db

  firebase:
    image: andreysenov/firebase-tools
    ports:
      - "127.0.0.1:9099:9099"
    command: firebase emulators:start --project descomplicai-3e611 --only auth

  # BACKEND (NODE + TSX)
  server:
    build: ./server
    container_name: node_server
    env_file:
      - .env
    ports:
      - "${BK_PORT}:${BK_PORT}"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      DB_HOST: db 

    depends_on:
      - db

  # FRONTEND (REACT DASHBOARD)
  client:
    build: ./client
    container_name: react_client
    env_file:
      - .env
    ports:
      - "${FT_PORT}:${FT_PORT}"
    stdin_open: true
    depends_on:
      - server

  # âœ… LANDING PAGE (VITE)
  landing_page:
    build:
      context: ../LandingPage
    container_name: vite_landing
    env_file:
      - .env
    ports:
      - "${LP_PORT}:${LP_PORT}"
    volumes:
      - ../LandingPage:/app
      - /app/node_modules
    stdin_open: true

volumes:
  postgres_data: